language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

install:
  - go mod download
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - go test -cover -race ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=coverage.out ./...
  - [ -n "$COVERALLS_TOKEN" ] && goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

sudo: false
