language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

install:
  - go mod download
  - make install-tools

script:
  - make format
  - git diff --exit-code
  - go mod tidy
  - git diff --exit-code
  - make test
  - make lint
  - make coverage.out
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

sudo: false
