on:
- push
- pull_request
name: test
jobs:
  lint:
    strategy:
      matrix:
        go-version:
        - 1.14.x
        os:
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.1
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      run: $(go env GOPATH)/bin/golangci-lint run ./...
